title: Jazzumm Jezzini | Blog
author: mwzaj
email: jazzumm.jezzini@gmail.com    
description: > # this means to ignore newlines until "baseurl:"
  Mi portafolio Jazzumm Jezzini

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  mwzaj # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
